image: node:8

# Set up MySQL test-database
services:
  - mysql:5.5

# Configure test-database
variables:
  MYSQL_DATABASE: mydb
  MYSQL_ROOT_PASSWORD: secret

# Run JEST tests
run_tests:
  stage: test
  script:
    - cd Server/
    - npm install
    - npm test
    - npm run flow
    - cd ../Klient/
    - npm install
    - npm test
    - npm run flow
